version: "3"

services:
  backend:
    build: ./backend
    ports:
      - 5010:5010
    volumes:
      - ./backend/package.json:/app/package.json:rw
      - ./backend/.env:/app/.env:rw
      - ./backend/src/:/app/src/:rw
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend/pages/:/app/pages/:rw
      - ./frontend/public/:/app/public/:rw
      - ./frontend/server/:/app/server/:rw
      - ./frontend/components/:/app/components/:rw
      - ./frontend/app.vue:/app/app.vue:rw
      - ./frontend/.env:/app/.env:rw
      - ./frontend/package.json:/app/package.json:rw

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: wahoot_db
      POSTGRES_USER: wahoot
      POSTGRES_PASSWORD: wahoot
      PGDATA: customDataFolder
    volumes:
      - ./dbData/:/var/lib/postgresql/data/customDataFolder
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d wahoot_db -U wahoot"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    ports:
      - 8080:8080
